ALTER TABLE `us_usuario`
ADD COLUMN `DS_DIRECCION`  varchar(200) NULL AFTER `DS_CORREO`;

ALTER TABLE `ft_factura`
DROP COLUMN `NM_CLIENTE_ID`,
ADD COLUMN `NM_CLIENTE_ID`  bigint(20) NULL AFTER `DT_FECHA_CREACION`;

ALTER TABLE `ft_factura` ADD CONSTRAINT `FK_CLIENTE_FACTURA` FOREIGN KEY (`NM_CLIENTE_ID`) REFERENCES `us_usuario` (`NM_DOCUMENTO_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `tp_producto`
ADD COLUMN `NM_ESTADO`  int(1) NULL AFTER `DT_FECHA_CREACION`;

ALTER TABLE `tp_producto`
ADD COLUMN `DB_PRECIO_VENTA_UND`  double NULL AFTER `NM_ESTADO`;

ALTER TABLE `tp_producto`
ADD COLUMN `NM_ELIMINADO`  int(1) NULL DEFAULT 0 AFTER `DB_PRECIO_VENTA_UND`;

ALTER TABLE `tp_inventario_producto`
DROP COLUMN `NM_PRECIO_UNITARIO_VENTA`;

ALTER TABLE `tp_producto`
ADD COLUMN `NM_PRECIO_UNITARIO_COMPRA_UND`  varchar(255) NULL AFTER `DB_PRECIO_VENTA_UND`;

ALTER TABLE `tp_inventario_producto`
DROP COLUMN `NM_PRECIO_UNITARIO_COMPRA`;

ALTER TABLE `tp_inventario_producto` DROP FOREIGN KEY `FK_VENDEDOR`;

ALTER TABLE `tp_inventario_producto`
MODIFY COLUMN `CS_VENDEDOR_PRODUCTO_ID`  bigint(20) NOT NULL AFTER `NM_CANTIDAD_INVENTARIO`;

ALTER TABLE `ft_factura`
MODIFY COLUMN `DS_CODIGO_FACTURA`  varchar(10) CHARACTER SET utf8 COLLATE utf8_spanish_ci NULL AFTER `CS_FACTURA_ID`,
CHANGE COLUMN `NM_ID_CLIENTE1` `NM_VENDEDOR_ID`  bigint(20) NOT NULL AFTER `DS_CODIGO_FACTURA`;

ALTER TABLE `ft_factura` ADD CONSTRAINT `FK_VENDDOR_FACTURA` FOREIGN KEY (`NM_VENDEDOR_ID`) REFERENCES `us_usuario` (`NM_DOCUMENTO_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `tp_inventario_producto` DROP FOREIGN KEY `FK_VENDEDOR`;

ALTER TABLE `tp_inventario_producto`
MODIFY COLUMN `CS_VENDEDOR_PRODUCTO_ID`  int(6) NOT NULL AFTER `NM_CANTIDAD_INVENTARIO`;

ALTER TABLE `tp_inventario_producto` ADD CONSTRAINT `FK_VENDEDOR` FOREIGN KEY (`CS_VENDEDOR_PRODUCTO_ID`) REFERENCES `tp_vendedor_producto` (`CS_VENDEDOR_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

