ALTER TABLE `ft_factura`
ADD COLUMN `NM_PRECIO_IVA`  double NULL AFTER `NM_PRECIO_TOTAL`;

ALTER TABLE `ft_factura`
ADD COLUMN `DS_CLIENTE`  varchar(200) NOT NULL AFTER `NM_CLIENTE_ID`;

ALTER TABLE `ft_factura_detalle`
ADD COLUMN `NM_PRECIO_UNITARIO`  double NULL AFTER `NM_PRECIO_TOTAL_PRODUCTO`;

ALTER TABLE `ft_factura_detalle`
ADD COLUMN `NM_ID_DETALLE_FACTURA`  int(5) NOT NULL AUTO_INCREMENT FIRST ,
ADD PRIMARY KEY (`NM_ID_DETALLE_FACTURA`);

